name: job-queue-infra
description: A minimal AWS Python Pulumi program for job-queue-system cloud infrastructure.
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
